# Generated by Django 4.2.4 on 2023-08-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_application_user_application_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(choices=[('Nigeria', 'Nigeria'), ('Ethopian', 'Ethopia'), ('Germany', 'Germany')], default='Nigeria', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='obi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
