# Generated by Django 4.2.4 on 2023-08-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_job_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
