# Generated by Django 4.2.4 on 2023-08-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(default='none.jpg', upload_to='applications'),
        ),
    ]
