# Generated by Django 4.2.4 on 2023-08-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('Nigeria', 'Nigeria'), ('Ethopian', 'Ethopia'), ('Germany', 'Germany')], default='Nigeria', max_length=20),
            preserve_default=False,
        ),
    ]
