# Generated by Django 4.2.4 on 2023-08-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_location_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
